### ISSUE TITLE
Wall removal bug

### ISSUE THREAD

**Issue by connor-golin** [UQcsse3200/2023-studio-2#201]
## Description
Placing walls in quick succession causes some walls to not remove/ghost.

## How To Reproduce
Steps to reproduce the behaviour:
1. Press `MOUSE3` to activate the building hammer.
2. Press `T` and the GUI wall icon with `MOUSE1`.
3. Place multiple walls in quick succession with `MOUSE1`.
4. Attempt to remove all walls with `MOUSE2`.
5. Observe some walls do not despawn from the game world.

## Expected Behaviour
Walls can be placed and removed without ghosting.

**Comment by rowan-gray** [comment]
Solved with commit f332770
