### ISSUE TITLE
Extractor textures black on removal

### ISSUE THREAD

**Issue by connor-golin** [UQcsse3200/2023-studio-2#214]
## Description
Placing extractors around the map and then right clicking to remove them currently causes all extractors to have a black sprite.

## How To Reproduce
Steps to reproduce the behaviour:
1. Enter the EarthGameArea by pressing `Start`
2. Press `3` to activate the building inventory tab
3. Press `T` to open the StructurePicker menu, then select the extractor.
4. Place any amount of extractors with `MOUSE1`
5. Remove an extractor by pressing `MOUSE2` while hovering the mouse over it.

## Expected Behaviour
`MOUSE2` on a placed extractor removes it from the game world with no black sprites or other external effects.

## Screenshots
![image](https://github.com/UQcsse3200/2023-studio-2/assets/94519823/0be378a4-ffc3-4ccb-afcb-e7b98a893360)

**Comment by mira-alford** [comment]
This isnt really a bug because extractors shouldnt even be able to be removed in the first place. However, it is a bug that extractors cant be removed.

**Comment by mira-alford** [comment]
Fixed
