### ISSUE TITLE
Players can repair walls/gates

### ISSUE THREAD

**Issue by khushijain0302** [UQcsse3200/2023-studio-2#28]
Task: [Players can repair walls/gates].
Feature: [Barricades/Wall](https://github.com/UQcsse3200/2023-studio-2/issues/14#6)

In this subfeature, players will have the ability to repair damaged walls and gates strategically placed to defend against enemy advancement and protect critical structures like the Ship/Extractor. This subfeature enables players to interact with damaged barricades, walls, and gates, restoring their integrity to maintain the defensive line against enemies.

Dependencies
Implement wall ticket(#18 )
Wall Sprite (https://github.com/UQcsse3200/2023-studio-2/issues/9)

Milestones
List of steps that need to be completed for this task.
Step1:Implement Wall Repair Mechanics(Aug 20)
Step2:Wall Repair Animation and Effects(Aug 20)
Step3:Logic Integration(Aug 21)
Step4:Player Resources(Aug 22)
Step5:Testing and Balancing (Aug 22)
Step6:Document(Aug 23)

Documentation
[Main description of feature](https://github.com/UQcsse3200/2023-studio-2/wiki/Game-Screens)
[JavaDoc](https://github.com/UQcsse3200/2023-studio-2/issues/JavaDoc/Location/Package/Class)
...
Member
Name (GitHub [khushijain0302](https://github.com/khushijain0302))

**Comment by lorenzopolicar** [comment]
Is this a duplicate?

**Comment by rowan-gray** [comment]
Yes. I'll close it now

**Comment by rowan-gray** [comment]
Duplicate task

**Comment by rowan-gray** [comment]
Duplicate ticket

**Comment by rowan-gray** [comment]
Not planned
