### ISSUE TITLE
Game Tutorial

### ISSUE THREAD

**Issue by khushijain0302** [UQcsse3200/2023-studio-2#315]
### **Game tutorial**
The purpose of this ticket is to implement a user tutorial component within the game to provide players with essential information and guidance on how to play the game effectively. The user tutorial will be designed to enhance the overall gaming experience by helping players understand game mechanics, controls, and objectives. It will appear as a pop-up window that appears at the beginning of the game or can be accessed from the game's main menu. The tutorial will cover various aspects of gameplay, including movement controls, placing structures (e.g., walls, turrets), resource management, and other important gameplay elements.

## SubFeature/component (optional)
**This ticket includes the following components:**

- Making Wiki for the user tutorial.
- Designing the user tutorial interface.
- Creating tutorial content and text.
- Implementing triggers to display the tutorial at the appropriate times.

## **Examples (optional)**

**Movement Controls**: The tutorial will explain how to move the character within the game using keyboard keys (e.g., W for up, A for left, S for down, and D for right).

**Placing Structures**: Players will be guided on how to place structures like walls and turrets to defend their base or navigate the game world.

**Resource Management**: The tutorial will introduce players to resource gathering and management mechanics, ensuring they understand how to collect and use resources effectively.

# **Milestones**
- [x] Goal 1: #325
- [ ] Goal 2: #326
- [ ] Goal 3: #327
- [x] Goal 4: #319 
- [ ] Goal 5: Documentation, Testing and bug fixes 

# **Members**
Khushi @khushijain0302 - Khushi Jain
Raghav @NotRaghavAggarwal - Raghav Aggarwal

**Comment by rowan-gray** [comment]
Delayed until next sprint

**Comment by rowan-gray** [comment]
Scrapped for this sprint
