### ISSUE TITLE
Optimising gameplay conditions/decisions 

### ISSUE THREAD

**Issue by yuvrajsingh001** [UQcsse3200/2023-studio-2#316]
# **Description**
The goal of this task is to optimize gameplay decisions and conditions, specifically focusing on win conditions and travel conditions within the game.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Win Condition optimisation
- [x] Travel condition optimisation
- [x] Testing

#### **Win Condition Optimization:**
   - Review and assess the current win conditions in the game.
   - Identify any inconsistencies or issues with the existing win conditions.
   - Propose and implement improvements to make win conditions more engaging and satisfying for players.
   - Ensure that win conditions are clear and achievable, avoiding frustrating or confusing gameplay moments.

#### **Travel Condition Optimization:**
   - Evaluate the mechanics related to player travel within the game world.
   - Analyze the efficiency and realism of travel conditions, such as movement speed, transportation methods, and navigation.
   - Consider the balance between convenience and challenge when optimizing travel conditions.

#### **Testing and Balancing:**
   - Conduct thorough testing of the modified win and travel conditions.
   - Gather feedback to fine-tune the changes.
   - Ensure that the changes do not introduce new bugs or issues to the game.
   - Balance the difficulty of achieving win conditions and the ease of travel to maintain an engaging gameplay experience.

#### Documentation
- to be added

**Comment by rowan-gray** [comment]
Delayed until sprint 4 due to the game not being complete enough to be able to effectively complete this ticket in sprint 3.

**Comment by rowan-gray** [comment]
Done last minute :/
