### ISSUE TITLE
Cost Balancing for Game Components

### ISSUE THREAD

**Issue by Yugansh-Uq** [UQcsse3200/2023-studio-2#317]
# **Description**
**Task:** [Cost Balancing](#318)
**Feature:** [Healing, Walls, Turrets, Resources](#318)

In this particular task, we will work on optimising healths of all components which are actionable in accordance with their respective healths. We will decide and work on setting health bars of components with regards to others while determining the extent of damaged caused to each component in a single attack by different enemies. Furthermore, we also want to assign different damaging capacities to different enemy types, which will ensure that different enemies cause different damage to player's health as well as components' health. For actually implementing all these changes, we might make some changes in config files. 

Another important task which we have to pay attention to is assigning costs to resources. This would ensure that there is cost involved in interaction and all interactions come at a cost of resources.
 
## **Example**

For example, placing a wall might require 2 units of any resources (to be determined); however, since turrets is more advanced option of defence against enemies, placing it might require more that 2 units of resources. 

# **Dependencies**

- [x] Healing.java
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Changes in config files (Sept 21)
- [x] Write code for healing in accordance with resources (Sept 23)

 
# **Documentation**
- To be added
- 
 
# **Member**
- Yugansh Pancholi (@Yugansh-Uq)

**Comment by rowan-gray** [comment]
Complete
