### ISSUE TITLE
Flashing Entities Above Player

### ISSUE THREAD

**Issue by rowan-gray** [UQcsse3200/2023-studio-2#331]
## Description
All entities above the player *and* above the bottom of the spaceship begin flashing.

## How To Reproduce
Steps to reproduce the behaviour:
1. Enter the Earth Game Area.
2. Walk up until you are above the spaceship.
3. Place any structures or lure any entities above the spaceship.
4. Walk below the entities or structures.
5. Entities and structures will flash.

## Expected Behaviour
Shouldn't be flashing.

## Video
https://github.com/UQcsse3200/2023-studio-2/assets/63951256/7b91b9cb-9b91-4452-852a-f42fd2de674a

**Comment by connor-golin** [comment]
they are indeed flashing

**Comment by mira-alford** [comment]
Seems fixed on main
