### ISSUE TITLE
Intro window resize bug

### ISSUE THREAD

**Issue by connor-golin** [UQcsse3200/2023-studio-2#332]
## Description
Resizing the window during the game intro causes red background.

## How To Reproduce
Steps to reproduce the behaviour:
1. Start the game by running `DesktopLauncher`
2. Click settings, and untick full screen.
3. Click exit, then click start.
4. During the intro, resize the game window and observe the bug.

## Expected Behaviour
The intro should resize with the window.

## Screenshots
![image](https://github.com/UQcsse3200/2023-studio-2/assets/94519823/576610d3-5b3a-47e1-81f7-5d6ddf8ca1ff)

## Temporary Fix
Start and run the game only in fullscreen.

**Comment by Tarushi263** [comment]
Fixed and pushed to story team's branch.

**Comment by Minirobbo** [comment]
This doesn't seem to be fixed??? Just tried this on the main branch. @Tarushi263

**Comment by Tarushi263** [comment]
I did fix it, it was working on story team's branch story1, but they've merged a different branch to main.
