### ISSUE TITLE
Tree Visual Bug Earth

### ISSUE THREAD

**Issue by rowan-gray** [UQcsse3200/2023-studio-2#340]
## Description
There is a visual bug for one of the trees on the right-hand side of the map where a single tile of the tree is missing.

## How To Reproduce
Steps to reproduce the behaviour:
1. Go to the ship on Earth
2. Walk right to the edge of the map
3. See error

## Screenshots
![image](https://github.com/UQcsse3200/2023-studio-2/assets/63951256/9856db61-80c8-47d5-867a-b51e5b3180a8)

**Comment by Tarushi263** [comment]
Fixed the bug. Commit it to the map team's branch?

**Comment by Tarushi263** [comment]
Fixed the bug by removing the tree and also a couple of other trees on the same map. Commit it to the map team's branch?
