### ISSUE TITLE
Tree Visual Bugs Lush Planet

### ISSUE THREAD

**Issue by rowan-gray** [UQcsse3200/2023-studio-2#341]
## Description
There is a visual bug for one of the trees at the spawning location in the Lush game area where half of one tree is missing, and there is a tree canopy without a trunk.

## How To Reproduce
Steps to reproduce the behaviour:
1. Go to the ship on Earth
2. Go to the second planet
3. See error at the bottom left of the screen.

## Screenshots
![image](https://github.com/UQcsse3200/2023-studio-2/assets/63951256/336383c7-da7b-44b0-ac48-a1578ae956f2)

**Comment by mira-alford** [comment]
Fixed! It was to do with the sprite being wrong, and having incorrect sizes. There is still a slight issue with flowers being on the layer though.
