### ISSUE TITLE
Companion animations

### ISSUE THREAD

**Issue by atharvagupta2003** [UQcsse3200/2023-studio-2#40]
# **Description**
**Task:** [Companion Animations].
**Feature:** [Companion sprint 1] (#7 )

Adding a basic animations for future features and levels. 
 

# **Dependencies**
-[] Companion initialisation on map (#38) 

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 - Created animations and static images that could be utilised in forthcoming sprints.

 
**Completion Deadline:** Aug 28.

 
# **Documentation**
- TBD
 
# **Member**
- Raghavendra Singh Gulia (RagGul)(tantrik8119)

**Comment by lorenzopolicar** [comment]
Please ensure you link the feature ticket this task ticket is referring to. Also, assign members and add labels to this.

**Comment by MaxwellSchroder** [comment]
Let's reduce the number of team members working on this to 2, ideally

**Comment by MaxwellSchroder** [comment]
This is an outdated ticket of sprint 1 not completed
