### ISSUE TITLE
Companion Fix Movement Animation

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#450]
# **Description**
**Task:** Companion Fix Movement Animation
**Feature:** #446 
This task is fixing the constant movement animation the companion experiences, even though it is stationary. 

**example**
When the companion is not moving, there should not have a movement animation playing.

# **Dependencies**
NONE 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Oct 7 - 9 ) 
- [x] Step 2 (Oct 10 - 12 ) 
- [x] Step 3 (Oct 13 -16) 
 
**Completion Deadline:** Oct. 16
 
# **Documentation**
- Main documentation : https://github.com/UQcsse3200/2023-studio-2/wiki/Companion
 
# **Member**
- Raghavendra(RagGul)
- Neil Barigye (@neil-nb)

**Comment by neil-nb** [comment]
I've since fixed this issue, so this ticket can be closed.
