### ISSUE TITLE
Companion low-health indicator stacking text

### ISSUE THREAD

**Issue by connor-golin** [UQcsse3200/2023-studio-2#459]
## Description
Text is being stacked when the companion takes damage, causing the indicator to be unreadable.

## How To Reproduce
Steps to reproduce the behaviour:
1. Enter the game.
2. Allow the companion to take damage multiple times.
3. Observe text stacking in the bottom left of the screen.

## Expected Behaviour
Text does not stack.

## Screenshots
![image](https://github.com/UQcsse3200/2023-studio-2/assets/94519823/6a0c8945-e4d4-48c6-914f-c5eabcfd91a8)

**Comment by MaxwellSchroder** [comment]
Bug has been fixed.
1. Location of alert is now above the "Companion" header on the screen.
2. There can only be one alert at one time
3. Alerts are disposed of properly now
4. The alerts remain on the screen for 1 second maximum
