### ISSUE TITLE
Planetary Order and Name Changes

### ISSUE THREAD

**Issue by YashMitttal** [UQcsse3200/2023-studio-2#512]
# **Description**
**Task:** Planetary Order and Name Changes
**Feature:** Planetary Order and Name Changes

Due to a new storyline, there have been significant changes in the planets' order and the planets’ names within the game. This task is a collaborative effort between our team and the space team to implement these changes. The story team has provided the updated planet order and names to align with the new narrative, and the space team will integrate these changes into the game.

# **Dependencies**
NA
 
# **Milestones**
List of steps that need to be completed for this task.

- [x] Finalisation of new names and order of planets according to the new story. (Oct 12)
- [x] Integration of the updated planetary order and names (Oct. 17)

**Completion Deadline:** Oct 17

# **Documentation**
TBD
 
# **Member**
- Yash Mittal (@YashMitttal} (s4823869)
- Thomas Day (TDay1) (Tom Day)

**Comment by henrybatt** [comment]
Duplicated with #476

**Comment by rachitchaurasia** [comment]
updated the deadlines :)

**Comment by YashMitttal** [comment]
done
