### ISSUE TITLE
Creating Saveable Components for all entities

### ISSUE THREAD

**Issue by Minirobbo** [UQcsse3200/2023-studio-2#526]
# **Description**

To ensure the ability to save and load all the entities from a game area, they all need to have a saveable component implemented correctly. This is to be completed by each team for the entities that concern that team.

# **Parts**
Each team is to mark off when their entities are completed and **pushed to main**.
- [x] Map Team
- [x] Enemies Team
- [x] Space Team
- [x] Player Team
- [x] Ships and Extractors Team
- [x] Buildables Team
- [x] Story Team
- [x] Companion Team
 
**Completion Deadline:** Oct 18.
 
# **Documentation**
- [Saveable Component](https://github.com/UQcsse3200/2023-studio-2/wiki/Saveable-Component)
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- Isaac (@Minirobbo)

**Comment by connor-golin** [comment]
[done](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by rachitchaurasia** [comment]
done :)

**Comment by rowan-gray** [comment]
Buildables done

**Comment by kk4w4i** [comment]
Done
Was able to implement it for the spawner as well

**Comment by rowan-gray** [comment]
Done yay
