### ISSUE TITLE
Walls & Gates

### ISSUE THREAD

**Issue by rowan-gray** [UQcsse3200/2023-studio-2#6]
# **Description**
The barricades/walls are going to be placeable objects which will prevent enemies from advancing through and destroying the Ship/Extractor (and any other damageable object). Gates can be placed to allow players to pass through a wall while preventing enemies from entering. There will be multiple different variants with different resource costs and different health properties to add an extra layer of progression to the game play.

## SubFeature/component
- The ability to repair walls (using resources)
- Gates which can be opened and closed by the player

## **Example**
- Walls will be placed around an extractor location to prevent enemies from reaching it and damaging it. Enemies will damage the wall in an attempt to reach the extractor, and if the player allows the wall to receive too much damage, it will break and allow enemies to pass.

# **Dependencies**
- Object placing
- Pathfinding system
- Damage/repair system
- Inventory system
- Extractors (for gameplay synergy)

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] #9
- [x] #18
- [x] #14
- [x] #23
- [x] #83 
- [x] #29
- [x] #27
- [x] #31
- [x] #21
- [x] #76 

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- [x] Improved sprite/s

# **Documentation**
- [Health Bar Component](../wiki/health-bar-component)
- [Proximity Activation Component](../wiki/proximity-activation-component)
- [Atlas Render Component](../wiki/atlas-render-component)
- [Joinable Component](../wiki/joinable-component)
- [Gate](../wiki/gates)
- [Walls](../wiki/wall)

# **Members**
- Rowan (@rowan-gray) (Rowan Gray)
- Yuvraj (@yuvrajsingh001) (Yuvraj Singh)
- Khushi (@khushijain0302) (Khushi Jain)
- Raghav (@NotRaghavAggarwal) (Raghav Aggarwal)
- Yugansh (@Yugansh-Uq) (Yugansh Pancholi)

**Comment by NotRaghavAggarwal** [comment]
Added documentation for wall and gates
